# Generated by Django 5.1.5 on 2025-01-20 08:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team1', models.CharField(max_length=100)),
                ('team2', models.CharField(max_length=100)),
                ('start_time', models.DateTimeField()),
                ('is_live', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team1_runs', models.IntegerField(default=0)),
                ('team2_runs', models.IntegerField(default=0)),
                ('team1_wickets', models.IntegerField(default=0)),
                ('team2_wickets', models.IntegerField(default=0)),
                ('overs', models.FloatField(default=0.0)),
                ('match', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='score', to='score_app.match')),
            ],
        ),
    ]
