# Generated by Django 5.1 on 2025-01-30 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('score_app', '0002_match_toss_decision_match_toss_winner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='toss_decision',
            field=models.CharField(blank=True, choices=[('bat', 'Bat'), ('bowl', 'Bowl')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='toss_winner',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
