# Generated by Django 5.1 on 2025-02-03 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('score_app', '0003_alter_match_toss_decision_alter_match_toss_winner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='toss_decision',
        ),
        migrations.AddField(
            model_name='match',
            name='batting_first',
            field=models.CharField(blank=True, choices=[('team1', 'Team 1'), ('team2', 'Team 2')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='toss_winner',
            field=models.CharField(blank=True, choices=[('team1', 'Team 1'), ('team2', 'Team 2')], max_length=10, null=True),
        ),
    ]
