# Generated by Django 5.1 on 2025-02-05 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('score_app', '0005_score_second_innings_started'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='score',
            name='second_innings_started',
        ),
        migrations.AddField(
            model_name='match',
            name='toss_decision',
            field=models.CharField(blank=True, choices=[('bat', 'Bat First'), ('bowl', 'Bowl First')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='batting_first',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='toss_winner',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
