# Generated by Django 5.1.5 on 2025-02-12 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('score_app', '0008_commentary_delete_player'),
    ]

    operations = [
        migrations.AddField(
            model_name='score',
            name='current_innings',
            field=models.IntegerField(default=1),
        ),
    ]
