# Generated by Django 5.1.5 on 2025-02-12 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('score_app', '0009_score_current_innings'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='winner',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
