# Generated by Django 5.1.5 on 2025-02-21 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('score_app', '0010_match_winner'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentary',
            name='overs',
            field=models.FloatField(default=0.0),
        ),
    ]
